name: .build-and-push-to-aws

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish -c Release
    - uses: actions/setup-node@v2.1.4 
    - name: build vue
      run: |
        export NODE_ENV=dev
        cd frontend
        npm install
        npm run build
        mkdir  ../LinkShorter/bin/Release/netcoreapp3.1/publish/wwwroot
        mv dist/* ../LinkShorter/bin/Release/netcoreapp3.1/publish/wwwroot
    - name: Get short SHA
      id: sha
      run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
    - name: Build and Push to ECR public
      id: build-and-push
      uses: pahud/ecr-public-action@8cd826db40befb59b0cd0b60b22a7ba72d06a7f7
      with:
        dockerfile: Dockerfile
        context: .
        create_repo: linkshorter
        tags: |
          public.ecr.aws/v1e8u6g7/linkshorter:latest
          public.ecr.aws/v1e8u6g7/linkshorter:${{ steps.sha.outputs.sha7 }}
